repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
releases:
  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    version: 1.16.1
    # disableValidationOnInstall: true
    values:
      - values.yaml
environments:
  dev: {}
  ci: {}
