podLabels:
  allowPrivilegedLevelCapabilities: "true"
  allowRunAsRoot: "true"
  allowBaselineLevelSeccompTypes: "true"
  allowBaselineLevelCapabilities: "true"
identity:
  issuer:
    scheme: kubernetes.io/tls
