controller:
  podAnnotations:
    linkerd.io/inject: enabled
  hostPort:
    enabled: true
  service:
    type: NodePort
  labels:
    allowHostPort: "true"
    allowPrivilegeEscalation: "true"
    allowBaselineLevelSeccompTypes: "true"
    allowRunAsRoot: "true"
    # for linkerd sidecar
    allowPrivilegedLevelCapabilities: "true"
    allowBaselineLevelCapabilities: "true"
  admissionWebhooks:
    patch:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    createSecretJob:
      securityContext:
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
    patchWebhookJob:
      securityContext:
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
