---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: app
  name: cert-secret
spec:
  secretName: cert-secret
  duration: 48h
  renewBefore: 25h
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  commonName: example.com
  dnsNames:
    - example.com
  isCA: true
  privateKey:
    algorithm: ECDSA
