---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  namespace: ingress
  name: awssm-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: ingress
  name: cert-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: awssm-secretstore
    kind: SecretStore
  target:
    name: cert-secret
    creationPolicy: Owner
    template:
      data:
        tls.key: |
          {{ .tlskey }}
        tls.crt: |
          {{ .tlscrt }}
  dataFrom:
    - extract:
        key: k8s-sec-playground
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  namespace: app
  name: awssm-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: app
  name: registry-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: awssm-secretstore
    kind: SecretStore
  target:
    name: registry-key
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .registry }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ .auth }}"
              }
            }
          }
  dataFrom:
    - extract:
        key: k8s-sec-playground
