---
secretGenerator:
  - name: awssm-secret
    namespace: app
    envs:
      - access-key.env
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: backend
    newName: kimitsu/kind-backend
    newTag: master@sha256:0b9267fc3d31bc7304bae1a0bd25ade93141345572fb89757201dec0b2fa8fef
resources:
  - namespace.yaml
  - network-policy.yaml
  - backend.yaml
  - ingress.yaml
  - external-secret.yaml
  - authz-policy.yaml
