---
secretGenerator:
  - name: db-secret
    namespace: app
    envs:
      - .env
configMapGenerator:
  - name: mysql-initdb-config
    namespace: app
    files:
      - mysql/init/1_create_table.up.sql
generatorOptions:
  disableNameSuffixHash: true
resources:
  - network-policy.yaml
  - backend.yaml
  - ingress.yaml
