repositories:
  - name: cert-manager
    url: https://charts.jetstack.io
releases:
  - name: cert-manager
    namespace: cert-manager
    chart: cert-manager/cert-manager
    version: v1.11.0
    values:
      - values.yaml
environments:
  dev: {}
  ci: {}
