name: conftest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  conftest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v1.34.0
      - run: |
          conftest pull https://github.com/YunosukeY/policy-for-pss/raw/master/bundle.tar.gz -p pss
          conftest test k8s/app -p pss
          helmfile template -f k8s/charts -e dev | conftest test -p pss -
          helmfile template -f k8s/charts/linkerd/helmfile.yaml -e dev | conftest test -p pss -
          helmfile template -f k8s/charts/cert-manager/helmfile.yaml -e dev | conftest test -p pss -
