name: conftest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  conftest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v2.14.0
      - run: |
          conftest pull https://github.com/YunosukeY/policy-for-pss/raw/master/bundle.tar.gz -p pss
          conftest test k8s/app -p pss
          helmfile template -f k8s/charts -e dev | conftest test -p pss -
          helmfile template -f k8s/charts/linkerd/helmfile.yaml -e dev | conftest test -p pss -
          helmfile template -f k8s/charts/cert-manager/helmfile.yaml -e dev | conftest test -p pss -
