name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  golangci-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.23.1
      - run: |
          golangci-lint run --out-format=github-actions
