name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  golangci-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.17.0
      - run: |
          golangci-lint run --out-format=github-actions
