name: kind e2e
on:
  push:
    branches:
      - master
    paths:
      - "cmd/**"
      - "internal/**"
      - "k8s/**"
      - "kind/**"
  pull_request:
    branches:
      - master
    paths:
      - "cmd/**"
      - "internal/**"
      - "k8s/**"
      - "kind/**"
jobs:
  kind:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v1.1.2
        with:
          aqua_version: v1.25.0
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - run: helm plugin install https://github.com/databus23/helm-diff
      - env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cat <<EOF > k8s/app/access-key.env
          access-key=$AWS_ACCESS_KEY
          secret-access-key=$AWS_SECRET_ACCESS_KEY
          EOF
          ./kind/e2e.sh run
