name: kind e2e
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  kind:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v2.12.1
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - run: helm plugin install https://github.com/databus23/helm-diff
      - env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cat <<EOF > k8s/app/access-key.env
          access-key=$AWS_ACCESS_KEY
          secret-access-key=$AWS_SECRET_ACCESS_KEY
          EOF
          ./kind/e2e.sh run
