name: yamllint
on:
  push:
    branches:
      - master
    paths:
      - '**.yaml'
      - '**.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.yaml'
      - '**.yml'
jobs:
  yamllint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - run: |
          yamllint -c .yamllint.yaml .
