name: yamllint
on:
  push:
    branches:
      - master
    paths:
      - '**.yaml'
      - '**.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.yaml'
      - '**.yml'
jobs:
  yamllint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: |
          yamllint -c .yamllint.yaml .
